version: '3.7'
services:
  mongodb_contenedor:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=practicas
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - data:/var/lib/mongodb
    ports:
      - 27017:27017
